version: '3.8'

services:
  mysql-server:
    image: node-project:1.0.0
    container_name: node_project_container
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER=user
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=node_mysqlserver
    ports:
      - "3000:3000"
    networks:
      - net-mysql-server
    volumes:
      - data-mysql-volume:/var/lib/mysql

networks:
  net-mysql-server: 

volumes:
  data-mysql-volume:
